### ISSUE TITLE
Store in postgres?

### ISSUE THREAD

**Issue by dagumak** [google/google-auth-library-ruby#101]
I'm thinking of writing a wrapper to store the tokens into Postgres, but are there reasons for why or why I shouldn't? In fact, is there a way for me to avoid token storage all together during the redirect process? I just want the access_token on the callback, and handle it in myself.

**Comment by ankitsinghaniyaz** [comment]
I just need the access and the refresh token, then I want the app to handle storing and loading it as required.

**Comment by Bartuz** [comment]
@dagumak have you made any progress on it? Want to move it forward

**Comment by RyanFerretti** [comment]
If anyone stumbles across this post, here is my first stab at a db backed store (just make sure **payload** is of type json):
`require 'googleauth/token_store'
class DbTokenStore < Google::Auth::TokenStore
	def load id
		token_scope(id)&.payload
	end

	def store id, token
		if existing = token_scope(id)
			existing.update(payload:token)
		else
			Token.create(user_id: id, provider: :google, payload:token)
		end
	end

	def delete id
		token_scope(id)&.destroy
	end
private
	def token_scope(user_id)
		Token.joins(:user).find_by(provider: :google, users: {id:user_id})
	end
end`

**Comment by vanboom** [comment]
Suggestion:  implement a manual token store class in this module to facilitate developers manually passing tokens from whatever storage they choose to use.

**Comment by askdesigners** [comment]
Yes a manual option would be ideal
