### ISSUE TITLE
How to validate Google ID tokens?

### ISSUE THREAD

**Issue by franklinyu** [google/google-auth-library-ruby#103]
Is it possible to validate Google ID token, as explained in [official documentation](https://developers.google.com/identity/sign-in/web/backend-auth)? Only Java, Node.js, PHP and Python examples are there. I need to validate the Google ID token passed by the client, as described in that page. Currently I think I can only decode the JWT myself.

**Comment by morgoth** [comment]
@franklinyu Take a look at https://github.com/google/google-id-token

**Comment by franklinyu** [comment]
@morgoth I prefer writing my own JWT verification code to relying on a gem not actively released.

**Comment by hxiong388** [comment]
[google-id-token v1.4.0](https://rubygems.org/gems/google-id-token) has been release. Please give it a shot see if it resolves your issue.

**Comment by dazuma** [comment]
The answer here is to use google-id-token. It isn't maintained as actively as some of the other libraries, but it is maintained.

**Comment by 5hanth** [comment]
as @dazuma pointed, `google-id-token` isn't actively maintained. can we consider reopen this issue?
