### ISSUE TITLE
Authentication isnt working

### ISSUE THREAD

**Issue by mustela** [google/google-auth-library-ruby#116]
Hi all, Ive created a simple ruby file with the code from the example for web authentication, but it isnt working as expected. It does redirects to google but when it comes back, it redirects me again to Google auth page, since `authorizer.get_credentials(user_id, request)` is always nil. 

Any clue? 

This is the [ruby file](https://gist.github.com/mustela/04b37dc2bb73d1cd53379f39faa3f960).

UPDATE: Redis is working, and creating a token manually too. Im using `ruby 2.3.4p301` and the last version of the gem.

**Comment by TheRoyalTnetennba** [comment]
@mustela are sessions enabled?  
```ruby
enable: sessions
```

**Comment by TheRoyalTnetennba** [comment]
Closing for now. Feel free to re-open if the previous commend was unable to solve your problem.
