### ISSUE TITLE
Service account with subject unauthorized

### ISSUE THREAD

**Issue by dlandau** [google/google-auth-library-ruby#123]
I'm updating a CLI directory management app from google-api-ruby-client 0.8 and having trouble replicating my previous workflow. 

From my understanding of https://developers.google.com/api-client-library/ruby/auth/service-accounts I believe I've satisfied all the setup requirements for a service account and granted Domain-wide Delegation. However, the following code fails with "Client is unauthorized to retrieve access tokens using this method."

```
scopes = ['https://www.googleapis.com/auth/admin.directory.user',
                'https://www.googleapis.com/auth/admin.directory.group']

authorizer = Google::Auth::ServiceAccountCredentials.make_creds(
  json_key_io: File.open(key_file_location),
  scope: scopes).dup

authorizer.sub = '<domain admin>'
authorizer.fetch_access_token!

```
If I don't set authorizer.sub the token is fetched successfully but further API calls fail with 403 responses.

**Comment by errpr** [comment]
I am also experiencing this issue with domain wide delegation. 
The response I get is:
```
irb(main):014:0>     auth_client.fetch_access_token!
Signet::AuthorizationError: Authorization failed.  Server message:
{
 "error": "unauthorized_client",
 "error_description": "Client is unauthorized to retrieve access tokens using this method."
}
```
I've tried the google-api-python-client library to make sure the account was set up correctly and I was able to make requests using that library.

**Comment by osfa** [comment]
I am also having this exact issue.

**Comment by reecebisel** [comment]
I was running into issues using the service account as well but I got it working with this bit of code. Please note that I was using the [google-api-ruby-client](https://github.com/google/google-api-ruby-client) to insert new users. 

```ruby
require 'google/apis/admin_directory_v1' . # this has to be required before you create the authorizer

authorizer = Google::Auth::ServiceAccountCredentials.make_creds(
  json_key_io: File.open(key_file_location),
  scope: 'https://www.googleapis.com/auth/admin.directory.user'
)
authorizer.sub = acting_admin_email 
authorizer.fetch_access_token!
directory = Google::Apis::AdminDirectoryV1::DirectoryService.new
directory.authorization = authorizer

# you have to wrap the user_params into the google user object otherwise the request will fail from # a bad json format

directory.insert_user(Google::Apis::AdminDirectoryV1::User.new(user_params))
```

**Comment by osfa** [comment]
I resolved my issue by removing all others types of credentials for the app in question (no oauth, just service account).

**Comment by salunn** [comment]
The error message would suggest that maybe you have not authorized your service account for the scope? Please check your Admin console -> security -> advanced settings and make sure your service account id has your scopes authorized.

**Comment by chris2x** [comment]
I am running into a very similar issue

require 'google/apis/admin_directory_v1'

authorizer = Google::Auth::ServiceAccountCredentials.make_creds(
  json_key_io: File.open("service.json"),
  scope: 'https://www.googleapis.com/auth/admin.directory.user'
)

authorizer.sub = '<admin email>'
authorizer.fetch_access_token!

service = Google::Apis::AdminDirectoryV1::DirectoryService.new
service.authorization = authorizer

user = User.find(account.user_id)

user_object = Google::Apis::AdminDirectoryV1::User.new
user_object.primary_email = account.name+'@'+account.domain;
user_object.name = Google::Apis::AdminDirectoryV1::UserName.new
user_object.name.given_name = account.first_name
user_object.name.family_name = account.last_name
user_object.change_password_at_next_login = true

response = service.insert_user(user_object)

and getting "Client is unauthorized to retrieve access tokens using this method."

it would appear to be permissions. I have:

add the app with the 'https://www.googleapis.com/auth/admin.directory.user' scope at 
Admin Console > Security > Manage API client access

enabled API access at 
Admin Console > Security > API Reference

Added the app as a Trusted app under (an no other non-standard apps)
Admin Console > Security > API Permissions under Admin

Created the service.json credentials as a service account at the https://console.developers.google.com/apis/dashboard

What am I missing?

**Comment by salunn** [comment]
Does your service account have domain-wide delegation authority enabled? Even after enabling it, you still need to have a real user account in the `authorizer.sub` property.

**Comment by chris2x** [comment]
yes, I have domain-wide delegation authority enabled on the service account and am using the email for a real account with admin privileges in the authorizer.sub property.

**Comment by salunn** [comment]
The make_creds call's param should be a hash, i.e. 
```ruby
authorizer = Google::Auth::ServiceAccountCredentials.make_creds({
      json_key_io: File.open("key.json"),
      scope: [Google::Apis::AdminDirectoryV1::AUTH_ADMIN_DIRECTORY_USER]
})
```

Also I'd probably set the client's authorization first, and then fetch the access token, just in case.

**Comment by chris2x** [comment]
salunn, can you clarify that last comment?

**Comment by salunn** [comment]
Instead of
 
```ruby
authorizer = Google::Auth::ServiceAccountCredentials.make_creds(
json_key_io: File.open("service.json"),
scope: 'https://www.googleapis.com/auth/admin.directory.user'
)

authorizer.sub = ''
authorizer.fetch_access_token!

service = Google::Apis::AdminDirectoryV1::DirectoryService.new
service.authorization = authorizer
```

I'd go with

```ruby
service = Google::Apis::AdminDirectoryV1::DirectoryService.new
service.authorization = Google::Auth::ServiceAccountCredentials.make_creds({
  json_key_io: File.open("service.json"),
  scope: 'https://www.googleapis.com/auth/admin.directory.user'
})

authorizer.sub = ''
authorizer.fetch_access_token!
```

But I admit that's just pure guessing.

**Comment by salunn** [comment]
You're welcome, I'm happy to try and render assistance. I'm not an actual contibutor though, and unfortunately have not really been through the codebase yet. By the way, you can use markdown to get your code-blocks more readable by pasting your code between three backticks: ```

Your error message is the exact same I got for three days before overcoming this obstacle. In my case it was because I had not set the `sub` property to an email that's an actual super admin in the Google organization.

My configuration:
In console.developers.google.com, logged in as an admin for the organization
* Enable the Admin SDK
* In IAM & Admin area, create a service account. If you don't have a project yet, the UI should guide you through creating one. Remember to check the Domain-wide Delegation on for the service account. After creating, copy down the Service Account ID visible in the Service Accounts view.
* In Apis & Services area, select credentials and create service account key for the service account you just created. Download the private key file.

In admin.google.com
* Security - Api Reference: Check the "Enable API access" checkbox
* Security - Advanced settings - Authentication: Follow the "Manage API client access link". In the next view, the client name is the Service Account ID you copied down earlier. The scope is the scope you're using in your code.

Those are the configuration steps I've had to take to get this gem working. You don't have to authorize a real user email with the service account, since the service account is the one that pretends to be someone else. There's an article on how they work at: https://cloud.google.com/iam/docs/understanding-service-accounts

**Comment by hinchy** [comment]
@chris2x: Wondering if you got to the bottom of this. I've been going round and round in circles for the last couple of days with the same problem. As far as I can tell, everything is configured as it should be ([SO question with all the details](https://stackoverflow.com/questions/49669540/another-401-when-impersonating-super-admin-using-service-account-with-admin-sdk))

**Comment by chris2x** [comment]
@hinchy as I recall I punted and went a different route

**Comment by hinchy** [comment]
@chris2x - Got it! Thanks for the response. For those that maybe stumble upon this, I eventually figured out my problem.

When I was authorizing the API client in Admin console, I was entering the "Service account ID", in my case: "REDACTED-320@gsuite-REDACTED.iam.gserviceaccount.com". Although this appears to work - the correct numerical ID appears (as shown in screenshot) - I was getting 401 errors.

However, when I entered the "client_id" from my private key file, in my case a number ending in 0381, and used the same scope, THEN I could authenticate successfully.

It's frustrating that entering the service account id didn't throw an error.

**Comment by nielsmouthaan** [comment]
Thanks @hinchy, spent way too long figuring out this was exactly mine issue too.

**Comment by mattwhisenhunt** [comment]
@dlandau, @errpr Have these comments helped you resolve your issue?

It looks like this thread could be closed unless anyone says differently.

**Comment by dlandau** [comment]
@mattwhisenhunt Thanks for checking. I rolled back to 0.8 and haven't tried again but could attempt another upgrade in the next few weeks.

**Comment by zcuneo** [comment]
Earth to Google. I love your products and APIs and want them to prevail. Please update your docs and UI for ManageOauthClients (AdminHome#OGX:ManageOauthClients).

Given how popular Google APIs are, this is likely costing countless hours and headaches while disillusioning thousands of developers globally every month. 

It's been over a year since @hinchy spelled this one out. A satisfactory solution would be as little as returning an error when the required "Client Name" or whatever that means (e.g. www.example.com? How would anybody misunderstand you want a string of digits?). For extra credit, the UI and docs could be updated to be more consistent.

**Comment by zcuneo** [comment]
Earth to Google. We love your products and APIs and want them to prevail. Please update your docs and UI for ManageOauthClients (AdminHome#OGX:ManageOauthClients).

![Screenshot from 2019-07-03 13-07-30](https://user-images.githubusercontent.com/13539117/60622224-95798300-9d94-11e9-96e9-d6e4ac4beb71.png)

**_Example: www.example.com_**  
How could anybody misinterpret this as anything but a string of digits? 

Given how popular Google APIs are, this is likely costing countless hours and headaches while disillusioning thousands of developers globally every month. 

It's been over a year since @hinchy [spelled this one out](https://github.com/googleapis/google-auth-library-ruby/issues/123#issuecomment-378992899). A satisfactory solution would be as little as returning an error when an invalid "Client Name" is submitted. For extra credit, the UI and docs could be updated to be more consistent.

Thanks in advance!

**Comment by yclian** [comment]
Thanks @salunn. Took me some time too and documented with some keywords here now: https://medium.com/@yclian/gotchas-api-access-to-google-admin-sdk-4cf5ed49540

**Comment by salunn** [comment]
Great, thanks for your effort!

**Comment by luisk182** [comment]
Im having a similar issue but with the calendar API.

I followed this steps:
 https://developers.google.com/admin-sdk/directory/v1/guides/delegation#delegate_domain-wide_authority_to_your_service_account

**And it worked for event creation and list events** 
but it doesnt when I try to add Attendees I get this error message:
**Service accounts cannot invite attendees without Domain-Wide Delegation of Authority**
I have authorized the service account from G suite api security console and enabled the "G Suite Domain-wide Delegation" in the API console.

Im not sure if the  "impersonated_email" must be the service account email or anyother

Here is my service account authentication code


`
   impersonated_email = 'myservice_account@service_account-calendar-test.iam.gserviceaccount.com'
    scope = 'https://www.googleapis.com/auth/calendar'

    authorizer = Google::Auth::ServiceAccountCredentials.make_creds(
      json_key_io: File.open('config/google/my_keys.json'),
      scope: scope
    )
    impersonate_auth = authorizer.dup
    impersonate_auth.sub = impersonated_email
`

**Comment by novoydarskiy** [comment]
The only answer you need to save 4 hours troubleshooting time https://github.com/googleapis/google-auth-library-ruby/issues/123#issuecomment-371745457

I had an issue when I try to switch app from `OAuth 2.0 Client IDs` to `Service Accounts`.
The problem was exactly that not all Scopes requested from Application were added into allowed scopes for Google Workspace Admin console.

Thank you @salunn!
