### ISSUE TITLE
I am unable to generate the generate the access code from service account credential.

### ISSUE THREAD

**Issue by knollies** [google/google-auth-library-ruby#133]
I am unable to generate the access token for a service account credential.
I have used the same example process, they had wrote in gem documentation.
```
scope = %w(https://www.googleapis.com/auth/firebase.database https://www.googleapis.com/auth/userinfo.email),
authorizer = Google::Auth::ServiceAccountCredentials.make_creds(
  json_key_io: File.open('/path/to/service_account_json_key.json'),
  scope: scope)
authorizer.fetch_access_token!
```
It is throwing following error.
`NoMethodError: undefined method `make_creds' for Google::Auth::ServiceAccountCredentials:Class`
when I browse through the class I din't find any methods make_creds.
may any one tell how to generate the access token from it

**Comment by bantini** [comment]
@knollies This is working for me
```ruby
require 'googleauth'
scope = %w(https://www.googleapis.com/auth/firebase.database https://www.googleapis.com/auth/userinfo.email),
authorizer = Google::Auth::ServiceAccountCredentials.make_creds(
  json_key_io: File.open('/path/to/service_account_json_key.json'),
  scope: scope)
authorizer.fetch_access_token!
```
Which version of the auth-library are you using?

**Comment by knollies** [comment]
I have installed gem with this process.
`gem  'googleauth'`
then I ran `bundle install` to install the gem.
replying to your question.
 ```
bundle list | grep googleauth
  * googleauth (0.1.0)
```

**Comment by bantini** [comment]
Can you try installing the latest version of this library?

**Comment by ilovemysillybanana** [comment]
I am having this same problem on the latest version

**Comment by dazuma** [comment]
@knollies The current version of the googleauth gem is 0.6.2. Please update your bundle to use that version.
