### ISSUE TITLE
Google Signin from server side app

### ISSUE THREAD

**Issue by rodrigopk** [google/google-auth-library-ruby#135]
I have a mobile app that is signin in with google and sending a server auth code to my backend app.
I want to use this code, along with the client secrets from the google developer console, to retrieve a refresh code for retrieving data from google drive when the user is offline.

I could not find the way to do this kind of authorisation using this library. If I'm missing something obvious, please let me know.
In the official documentation, I could find an example of how to do this on python:

```python
from oauth2client import client
    
# Exchange auth code for access token, refresh token, and ID token
credentials = client.credentials_from_clientsecrets_and_code(
CLIENT_SECRET_FILE,
['https://www.googleapis.com/auth/drive.appdata', 'profile', 'email'],
auth_code)
```
I would like to do this in ruby through a post to their `https://www.googleapis.com/oauth2/v4/token` endpoint. Here is what I've tried so far:
```
require 'uri'
require 'net/http'
require 'json'
    
url = URI("https://www.googleapis.com/oauth2/v4/token")
    
http = Net::HTTP.new(url.host, url.port)
http.use_ssl = true    

headers = {'Content-Type': 'application/json'}
request = Net::HTTP::Post.new(url.request_uri, headers)

request.body = {
  code: "#{server_auth_code_sent_to_api}",
  client_id: "#{client_id_from_developer_console}",
  client_secret: "#{client_secret_from_developer_console}",
  grant_type: 'authorization_code',
  redirect_url: '',
}.to_json
    
response = http.request(request)
puts JSON.parse(response.read_body)
```
But I keep getting the following error:
```
{
  "error": "unsupported_grant_type",
 "error_description": "Invalid grant_type: "
}
```
Does anybody has an idea on what I'm doing wrong, or has a working example on how to do this kind of authorisation?
Thanks in advance.

**Comment by TheRoyalTnetennba** [comment]
Sorry for the delayed response, are you still experiencing this issue?

**Comment by rodrigopk** [comment]
@TheRoyalTnetennba I found that there was an issue with my request. What caused the request to fail was the Content-Type, and not the grant_type parameter. Digging around in the code for the client library I saw that the endpoint expects an `application/x-www-form-urlencoded` content type (I could not find this information on the docs).  
I adjusted my code accordingly and was able to get a successful response with the valid credentials and token. Here follows the resulting code:

```
require 'uri'
require 'net/http'
require 'json'

url = URI("https://www.googleapis.com/oauth2/v4/token")

params = {
    "code" => "#{server_auth_code_sent_to_api}",
    "client_id" => "#{client_id_from_developer_console}",
    "client_secret" => "#{client_secret_from_developer_console}",
    "grant_type" => "authorization_code",
    "redirect_url" => "#{redirect_url_from_developer_console}",
}

response = Net::HTTP.post_form(url, params)

puts JSON.parse(response.read_body)
```
