### ISSUE TITLE
Impersonate a user account using service account.

### ISSUE THREAD

**Issue by heedspin** [google/google-auth-library-ruby#136]
I'd like my service account to create google drive documents and change ownership to a user in my domain.  To accomplish this, I believe I need to delegate domain-wide authority to the service account and then create the document "as that user".  

I'm not sure how to specify the "user to impersonate".  The java APIs appear to have a setServiceAccountUser method which I believe is what I need.  How could I accomplish this with the Ruby API?

Thanks!

**Comment by salunn** [comment]
```ruby
client = Google::Apis::AdminDirectoryV1::DirectoryService.new
  client.authorization = Google::Auth::ServiceAccountCredentials.make_creds({
    json_key_io: File.open('./mykey'),
    scope: SCOPE
})
client.authorization.sub = faked.user@test.tld
client.authorization.fetch_access_token!
```

should do the trick.

**Comment by heedspin** [comment]
Boom!  That worked!

Thank you!
