### ISSUE TITLE
Need tag "google-auth-library-ruby" in StackOverflow

### ISSUE THREAD

**Issue by mpz** [google/google-auth-library-ruby#138]
In readme.md:

>  Don't hesitate to ask questions about the client or APIs on StackOverflow.

But it is need 1500 reputation on  StackOverflow for new tag "google-auth-library-ruby"

Can anyone please create such tag?

**Comment by Bartuz** [comment]
I've requested new tag. Need approval from moderators (20k rep + ?). https://stackoverflow.com/questions/tagged/google-auth-library-ruby

**Comment by TheRoyalTnetennba** [comment]
It's been [added](https://stackoverflow.com/questions/tagged/google-auth-library-ruby)
