### ISSUE TITLE
How to use API keys?

### ISSUE THREAD

**Issue by stiller-leser** [google/google-auth-library-ruby#140]
Due to our setup we cannot use the json file for authentication. Which steps would be neccessary to be able to use an API key instead?

**Comment by JustinBeckwith** [comment]
Greetings!  The answer to this really depends on the API you're trying to use.  Only a small number of Google APIs support the use if API keys.  May I ask - why doesn't json file based auth work for you?

**Comment by stiller-leser** [comment]
Hi there! It's been a while and by now we're using the JSON key for the Compute and GKE APIs, however let me describe our usage scenario:

We implemented a microservice that has access to multiple Google projects to deploy various things in these. Since we need a different key for every project, we are currently sending this key from one microservice (where the user trigger a deployment - simple web interface which has the keys) to the aformentioned deployment microservice (which does not know about the keys). Since the JSON key is bigger than a potential API key, it would have been nice to be able to use an API key instead (especially since we had issues to stringify the json key from time to time).

So from my side it is solved for us :)

stiller-leser

**Comment by JustinBeckwith** [comment]
Got it 👍 Thanks for follow up!
