### ISSUE TITLE
[Bug] CLIENT_ID_VAR in default_credentials.rb scoped incorrectly 

### ISSUE THREAD

**Issue by dturn** [google/google-auth-library-ruby#153]
It looks like #145 introduced a minor bug. When calling `Google::Auth.get_application_default(scopes)` there is a code path (`new` -> `from_env` -> `make_creds(scope: scope)`)  that hits: 
 https://github.com/google/google-auth-library-ruby/pull/145/files#diff-213fdc02c21601908a9d0b021cbf527fR56 and raises

```
Message: <"Unable to read the credential file specified by GOOGLE_APPLICATION_CREDENTIALS: uninitialized constant Google::Auth::DefaultCredentials::CLIENT_ID_VAR\nDid you mean?  Google::Auth::ClientId">
---Backtrace---
/Users/dturner/.gem/ruby/2.3.3/gems/googleauth-0.6.3/lib/googleauth/credentials_loader.rb:94:in `rescue in from_env'
/Users/dturner/.gem/ruby/2.3.3/gems/googleauth-0.6.3/lib/googleauth/credentials_loader.rb:84:in `from_env'
/Users/dturner/.gem/ruby/2.3.3/gems/googleauth-0.6.3/lib/googleauth/application_default.rb:57:in `get_application_default'
```

I believe the fix is to change the scope of the constant e.g.: `Google::Auth::CredentialsLoader::CLIENT_ID_VAR` instead of just `CLIENT_ID_VAR`

**Comment by TheRoyalTnetennba** [comment]
Resolved https://github.com/google/google-auth-library-ruby/pull/154

**Comment by dturn** [comment]
Thank you
