### ISSUE TITLE
EOL warning is loud for non-EOL ruby versions

### ISSUE THREAD

**Issue by wlipa** [google/google-auth-library-ruby#160]
Printing this at every startup is a pretty invasive warning for a ruby version which is not EOL for another 9 months:

    WARNING: You are running Ruby 2.3.7, which is nearing end-of-life.
    The Google Cloud API clients work best on supported versions of Ruby. Consider upgrading to Ruby 2.4 or later.
    See https://www.ruby-lang.org/en/downloads/branches/ for more info on the Ruby maintenance schedule.
    To suppress this message, set the GOOGLE_CLOUD_SUPPRESS_RUBY_WARNINGS environment variable.

**Comment by TheRoyalTnetennba** [comment]
Thanks for the feedback. I agree that it's loud. We're taking a stricter approach towards ruby version support than we have in the past and we feel it's important to let the users know well in advance. Do you have any suggestions for making the warnings less visible once a user understands the change in version support?

**Comment by wlipa** [comment]
I would consider putting it in the gem post-install message for ruby versions that are still maintained.  

As it is, I'm going to have to look at this message 30 times a day unless I define your custom environment variable across all hosts.  Gets kind of old, especially since I don't agree that indirect gem dependencies should take responsibility upon themselves for nagging me about ruby versions.  Couldn't every gem make the same argument that it should nag me?

**Comment by TheRoyalTnetennba** [comment]
Fair enough. Moving the warning to a post-install message on signet https://github.com/google/signet/pull/110
