### ISSUE TITLE
Add ability to authenticate a service account via environment variables instead of json file

### ISSUE THREAD

**Issue by haabaato** [google/google-auth-library-ruby#27]
Due to project requirements, I can't store files with tokens on the server, so all credentials have to read from environment variables.  Adding an initializer to ServiceAccountCredentials that accepts private_key & client_email as arguments instead of reading them from a file would be preferable. [#L66](https://github.com/google/google-auth-library-ruby/blob/master/lib/googleauth/service_account.rb#L66)

I can open a PR if the above solution would work.

**Comment by tbetbetbe** [comment]
Please send the PR - I think what you propose should be OK, we can flesh out the details in a PR.

**Comment by tbetbetbe** [comment]
This was resolved in #28
