### ISSUE TITLE
Missing loading pkcs keys

### ISSUE THREAD

**Issue by professor** [google/google-auth-library-ruby#32]
I'm upgrading code from 0.8 to 0.9. I'm not finding where this method is in the new auth api:  Google::APIClient::KeyUtils.load_from_pkcs12

Context: I'm deploying ruby code to heroku for service account access to Google Admin SDK. Since the code base is open source, I can not store the json file or pkcs12 on the filesystem. I see that in Issue 27 you added support for reading a json file from environment variables, but I'm having a deuce of a time formatting the json so that it can be stored as an environment variable. As such, I'd like to be able to pull in a pkcs12 key from an environment variable.

**Comment by sqrrrl** [comment]
In console.developers.google.com -> credentials you can just click on 'Generate new JSON key' for your existing service account to download a new key in the new format.

I'm a little reluctant to restore key_utils.rb in the client lib given the new format is preferred, but can if you really need it. File a bug on google/google-api-ruby-client if you do.

**Comment by professor** [comment]
Thank you for your help, I will close this issue since I opened one here:
https://github.com/google/google-auth-library-ruby/issues/38

For this application, I decided to go with 0.8 since I couldn't solve my problem with 0.9 with a rails app on heroku.

**Comment by sqrrrl** [comment]
Let me know what problems you had with rails/heroku. Feel free to drop me a note at sqrrrl at gmail
