### ISSUE TITLE
DefaultCredentials.from_env requires ENV_VAR to be GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by professor** [google/google-auth-library-ruby#37]
If I'm developing for multiple systems on my laptop, it would be nice to be able to use different json files for each system. The current implementation requires the ENV_VAR to be GOOGLE_APPLICATION_CREDENTIALS, and is not customizable.

**Comment by greggroth** [comment]
I'd recommend using a tool like [dotenv](https://github.com/bkeepers/dotenv) to manage the environment variables for each project.

**Comment by sqrrrl** [comment]
+1 to using dotenv or just simple shell scripts for different configs.

**Comment by professor** [comment]
I don't think that a ruby library should have strong opinions on application environmental variables. I'd argue that the application developer should be making those decisions. I guess we'll have to agree on disagreeing.

**Comment by greggroth** [comment]
The use of the `GOOGLE_APPLICATION_CREDENTIALS` environment variable [was not made by the ruby library maintainers](https://developers.google.com/identity/protocols/application-default-credentials) and is present in other the Google Auth libraries (e.g. [java client library](https://developers.google.com/api-client-library/java/google-api-java-client/reference/1.19.1/com/google/api/client/googleapis/auth/oauth2/GoogleCredential)).  It would be more confusing to break from this convention.

**Comment by tbetbetbe** [comment]
Closing this:

> The use of the GOOGLE_APPLICATION_CREDENTIALS environment variable was not made by the ruby library maintainers

+1 to using dotenv
