### ISSUE TITLE
Release 0.4.2?

### ISSUE THREAD

**Issue by kri5** [google/google-auth-library-ruby#41]
I'd like to know if you plan a release of a 0.4.2 version, as it contains a fix for relaxing the version constaints on the multi_json gem, that impacts the use of this library with chef-provisioning and the chefdk.

**Comment by tbetbetbe** [comment]
Hi, I plan to roll out a release later this week.  Sorry for the slow response!

**Comment by haabaato** [comment]
Thanks!  I also could use the functionality I introduced for reading credentials from environment variables.

**Comment by Temikus** [comment]
Gentle bump. Any news on this?
We're already getting StackOverflow questions:
http://stackoverflow.com/questions/31652250/knife-google-plugin-setup-issue

**Comment by tbetbetbe** [comment]
#45 resolves this
