### ISSUE TITLE
Retrieve GCE project_id?

### ISSUE THREAD

**Issue by blowmage** [google/google-auth-library-ruby#43]
Is it possible for Google::Auth::GCECredentials to retrieve `project_id` as well as fetching the access token? My understanding is that the `project_id` can be accessed from http://metadata.google.internal/computeMetadata/v1/project/project_id when running on a Compute Engine instance.

Not sure if we should look to googleauth for this, or if we should implement it ourselves. Thanks!

**Comment by icco** [comment]
You should implement yourself, that url is only accessible from your local google compute engine instance. It doesn't even require auth, you can hit that url with a simple http get and to retrieve the data you want.

https://cloud.google.com/compute/docs/metadata

**Comment by blowmage** [comment]
Thanks!
