### ISSUE TITLE
Jwt Access Credentials should cache JWTs

### ISSUE THREAD

**Issue by anthmgoogle** [google/google-auth-library-ruby#46]
The JWT Access Credentials should temporarily cache JWTs. Suggested algorithm:
- Hash JWTs using Audience as key.
- Also store the timestamp of last use with each JWT.
- On access clear any JWT unused for more than 1 hour.

**Comment by dazuma** [comment]
@anthmgoogle Hey Anthony, we're working on clearing the issue backlog. Is this still relevant?

**Comment by anthmgoogle** [comment]
No concern with closing this issue.
