### ISSUE TITLE
ServiceAccountCredentials initialize does not pass additional options to parent

### ISSUE THREAD

**Issue by jledwith** [google/google-auth-library-ruby#49]
I'm using the ServiceAccountCredentials to authenticate a service account. I also need to specify the 'sub' parameter to set the email address of a delegated account. Using the code:
```ruby
client = Google::Auth::ServiceAccountCredentials.new(json_key_io: json_key_io, scope: scope, sub: 'user@example.com')
``` 
The sub parameter is not passed to the parent class. I need to specify it manually in a separate step like this:
```ruby
client = Google::Auth::ServiceAccountCredentials.new(json_key_io: json_key_io, scope: scope)
client.update!(sub: 'user@example.com')
```

**Comment by sqrrrl** [comment]
Should be fixed by #50 if/when that gets merged.
