### ISSUE TITLE
Support for plain OAuth 2.0.

### ISSUE THREAD

**Issue by dsignr** [google/google-auth-library-ruby#69]
Hi, does this library provide support for plain OAuth 2.0 mentioned in the docs here?https://developers.google.com/identity/choose-auth

Edit: To clarify, I'd like to let my users sign-in using their google account just like the way slack does: 

1) Redirect the user to google's login form,
2) User signs in,
3) Redirect to callback URL,
4) Sign-in the user to the host application.

This was possible using the deprecated (http://www.rubydoc.info/github/google/google-api-ruby-client/Google/APIClient/ClientSecrets) `Google::APIClient::ClientSecrets` way as provided in the example here:

``` ruby
require 'google/apis/drive_v2'
require 'google/api_client/client_secrets'

client_secrets = Google::APIClient::ClientSecrets.load
auth_client = client_secrets.to_authorization
auth_client.update!(
  :scope => 'https://www.googleapis.com/auth/drive.metadata.readonly',
  :redirect_uri => 'http://www.example.com/oauth2callback'
)
```

But now, the docs point out to using the sign-in button as mentioned here:

https://developers.google.com/api-client-library/ruby/auth/web-app

which requires that: 

1) Users click on the sign in button
2) Google sign-in button popups-up the Google login form using JS,
3) User signs in,
4) Popup closes, calls-back JS function with user ID and ID token
5) My application makes another request to Google's token verification end-point
6) Google verifies ID of the user and my application signs in the user.

But isn't this more complicated and adds more points of failures to watchout for? Including:

1) What happens when the user doesn't have JS enabled?
2) My application makes an additional request to Google's servers to verify ID token, which may fail the sign in process if there's a network issue, etc.

Thanks!

**Comment by TheRoyalTnetennba** [comment]
Sorry for the long delay. That flow is talked about [https://github.com/google/google-auth-library-ruby#example-web](https://github.com/google/google-auth-library-ruby#example-web). Closing for now, but feel free to ping if you have any additional questions.
