### ISSUE TITLE
Load JSON file's content on Heroku?

### ISSUE THREAD

**Issue by bodaonline** [google/google-auth-library-ruby#78]
Hi

it seems to me that the credentials_loader.rb insists on a file but on Heroku there are those nice config vars. Can the credentials_loader.rb somehow be tricked to accept a config var instead of 

```
ENV["GOOGLE_APPLICATION_CREDENTIALS"] = "api-test-key.json" 
```

I managed to put the JSON's contents in a heroku config var nicely and can get it by calling 

```
puts ENV["GOOGLE_APPLICATION_CREDENTIALS"]
```

Thanks!

**Comment by coreyward** [comment]
After adding your JSON authorization file to Heroku ([walkthrough here](https://coreyward.svbtle.com/how-to-send-a-multiline-file-to-heroku-config)), you can create credentials like this:

```ruby
Google::Auth::ServiceAccountCredentials.make_creds(
  scope: 'https://www.googleapis.com/auth/drive',
  json_key_io: StringIO.new(ENV['GOOGLE_APPLICATION_CREDENTIALS'])
) 
```

Note that `StringIO` does just what it sounds like: provides IO-like access to a String object, which is what you want in order to let `Google::Auth` do its thing under the hood without requiring a disk-backed file object.

**Comment by beldaGR** [comment]
Good solution, but the need for either a path to a file or an IO object is bad design. Maybe people don't want to check their credential files in or host them

**Comment by neycodes** [comment]
@beldaGR Agreed, but try telling that to Google.

**Comment by mgnaresh** [comment]
how do I do this for Python please...am going nutts with it -;)

**Comment by coreyward** [comment]
@mgnaresh The internet is a great, big, wonderful place. Your contribution is a vague question on a Ruby-library asking about how to do something in Python. Kinda sad, right?

**Comment by mgnaresh** [comment]
yup...u surely are sad...I have deleted my comment sire !

**Comment by wapnen** [comment]
@coreyward i tried your solution, it starts setting the variable then it outputs "name is too long (maximum is 255 characters) name is invalid! is there any way to change the limit ?

**Comment by coreyward** [comment]
@wapnen I suspect you're missing the double quotes surrounding the command. Don't do this: `FOO=$(< ./your/file)`, do this: `FOO="$(< ./your/file)"` (note the quotes).

**Comment by neosepulveda** [comment]
@coreyward It works like a charm

**Comment by caro2692** [comment]
@coreyward should this solution work for a node application as well? I successfully completed the first step but am having issues with the second.

**Comment by dazuma** [comment]
Has your question been answered?

**Comment by optimus65537** [comment]
When passing a googleauth credentials object, in this case service account credentials, to Google::Cloud::Language it complains. Still manages to authenticate and get the desired response from the API but it throws this: 

**Invalid value #<Google::Auth::ServiceAccountCredentials**:0x000055... @project_id=......> **for key :credentials.** **Setting anyway.**

CREDS env contains my json key content

```ruby
auth = Google::Auth::ServiceAccountCredentials.make_creds(
scope: 'https://www.googleapis.com/auth/cloud-language',
json_key_io: StringIO.new(ENV['CREDS'])
)
Google::Cloud::Language.configure do |config|
config.credentials = auth
end
@google_language_service ||= Google::Cloud::Language.language_service
```

Thoughts?

Thanks!
