### ISSUE TITLE
Retry fetch_access_token! if connection fails

### ISSUE THREAD

**Issue by blowmage** [google/google-auth-library-ruby#89]
We have [a report of access_tokens not being fetched due to failed connection](https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/896). The user indicates that the request should be automatically retried in this circumstance. Can you implement a retry mechanism with an incremental backoff while fetching access_tokens?

**Comment by serihiro** [comment]
I think this issue is solved at #97 . Could you close this issue ? @hxiong388
