### ISSUE TITLE
Use a token store with ServiceAccountCredentials

### ISSUE THREAD

**Issue by 23tux** [google/google-auth-library-ruby#91]
Hi,

I have a questions regarding the use of `ServiceAccountCredentials`, alas there is no documentation:

Is it possible to use a token store with `ServiceAccountCredentials`? I don't find any helpful hints in the `#make_creds` methods https://github.com/google/google-auth-library-ruby/blob/master/lib/googleauth/service_account.rb#L56 nor in the initializer.

Correct me if I'm wrong, but I isn't it a good idea to reuse the access tokens when doing multiple requests, regardless of the underlying auth mechanism? The documentation shows a sample code for `WebUserAuthorizer`, but not for `ServiceAccountCredentials`.

Hope somebody can help me,
thx!

**Comment by hxiong388** [comment]
closed by #110
