### ISSUE TITLE
UserAuthorizer saves and loads "expires_at" field for OAuth2::Client, this will not be updated on token refresh

### ISSUE THREAD

**Issue by pavelbulanov** [google/google-auth-library-ruby#93]
Currently `UserAuthorizer `class saves `expires_at `field in `store_credentials `[method](https://github.com/google/google-auth-library-ruby/blob/master/lib/googleauth/user_authorizer.rb#L240), which in the first time when token was created (e.g. from authorization code) is a _calculated_ field in `Signet::Client` unless not set explicitly.
  ```
json = MultiJson.dump(
          client_id: credentials.client_id,
          access_token: credentials.access_token,
          refresh_token: credentials.refresh_token,
          scope: credentials.scope,
          expiration_time_millis: credentials.expires_at.to_i * 1000
        )
```

  ```
    def expires_at
        if @expires_at
          @expires_at
        elsif @issued_at && @expires_in
          return @issued_at + @expires_in
        else
          return nil
        end
      end

```

`UserAuthorizer` then uses this stored value in `get_credentials` call [here](https://github.com/google/google-auth-library-ruby/blob/master/lib/googleauth/user_authorizer.rb#L147) and put it explicitly to new `UserRefreshCredentials` object. This time it will have explicit value and not calculate `expires_at` properly.

```
credentials = UserRefreshCredentials.new(
          client_id: @client_id.id,
          client_secret: @client_id.secret,
          scope: data['scope'] || @scope,
          access_token: data['access_token'],
          refresh_token: data['refresh_token'],
          expires_at: data.fetch('expiration_time_millis', 0) / 1000
        )
```

Later, when token will be refreshed because of expiration, `expire_at` field won't get updated because Google will explicitly return `expires_in` only in return for token refresh call. And `Signet::Client` doesn't update `expires_at` if it was not set explicitly (and it's not). So `expires_at `will remain to be old value, explicitly set by `UserAuthorizer` before. See [here](https://github.com/google/signet/blob/master/lib/signet/oauth_2/client.rb#L736):
 ```
   def expires_in=(new_expires_in)
        if new_expires_in != nil
          @expires_in = new_expires_in.to_i
          @issued_at = Time.now
        else
          @expires_in, @issued_at, @expires_at = nil, nil, nil
        end
      end
```

Same time, `expires_within?` method (used each `apply!` call to verify if token expired) checks for `expires_at` method, which will use explicit value if it was set (and calculated value only if not set). So in `apply!` method it will think that token has expired because checking against `expires_at` value, although it was just updated (but hasn't updated `expires_at `field).

**Comment by dazuma** [comment]
Hi! Sorry for the slow response here. Is this still an issue for you?
